export default interface IMessage {
    message_id: number,
    from_user?: IUser,
    date: number,
    chat: IChat,
    forward_from?: IUser,
    forward_from_chat?: IChat,
    forward_from_message_id?: number,
    forward_signature?: string,
    forward_date?: number,
    reply_to_message?: IMessage,
    edit_date: any,
    media_group_id: any,
    author_signature: any,
    text: string,
    entities: any,
    caption_entities: any,
    audio: any,
    document: any,
    photo: any,
    sticker: any,
    video: any,
    video_note: any,
    voice: any,
    caption: any,
    contact: any,
    location: any,
    venue: any,
    animation: any,
    dice: any,
    new_chat_member: any,
    new_chat_members: any,
    left_chat_member: any,
    new_chat_title: any,
    new_chat_photo: any,
    delete_chat_photo: any,
    group_chat_created: any,
    supergroup_chat_created: any,
    channel_chat_created: any,
    migrate_to_chat_id: any,
    migrate_from_chat_id: any,
    pinned_message: any,
    invoice: any,
    successful_payment: any,
    connected_website: any,
    json: {
        message_id: number,
        from: {
            id: number,
            is_bot: boolean,
            first_name: string,
            language_code: string
        },
        chat: {
            id: number,
            first_name: string,
            type: string
        },
        date: number,
        text: string
    }
    content_type: string,
}

interface IUser {
    id: number,
    is_bot: boolean,
    first_name: string,
    last_name?: string,
    username?: string,
    language_code?: string,
    can_join_groups?: boolean,
    can_read_all_group_messages?: boolean,
    supports_inline_queries?: boolean
}

interface IChat {
    id: number,
    type: string,
    title?: string,
    username?: string,
    first_name?: string,
    last_name?: string,
    photo?: any,
    description?: string,
    invite_link?: string,
    pinned_message?: IMessage,
    permissions?: any,
    slow_mode_delay?: number,
    sticker_set_name?: string,
    can_set_sticker_set?: boolean
    all_members_are_administrators?: any,
}
