---
name: Merge CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          context: .
