---
name: ci

on:
  push:
    branches:
      - 'ci'

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: bbalkonsky
          password: ${{ secrets.GH_PAT }}
          repository: bbalkonsky/muz-bot-js
          dockerfile: Dockerfile
          tags: |
            bbalkonsky/muz-bot-js:${{ github.sha }}
            bbalkonsky/muz-bot-js:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - push-to-ghcr
    steps:
      - name: Hook to server
        run: curl https://${{ secrets.DEPLOY_URL }}/muz-js-bot