---
name: ci

on:
  push:
    branches:
      - 'ci'

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bbalkonsky/muz-bot-js:${{ github.sha }}
            ghcr.io/bbalkonsky/muz-bot-js:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - push-to-ghcr
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    steps:
      - name: Hook to server
        run: curl "https://${{ env.DEPLOY_URL }}/muz-js-bot"