---
name: ci

on:
  push:
    branches:
      - 'ci'

jobs:
  upload-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: bbalkonsky
          password: ${{ secrets.GH_PAT }}
          repository: bbalkonsky/muz-bot-js
          dockerfile: Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            bbalkonsky/muz-bot-js:${GITHUB_SHA}
            bbalkonsky/muz-bot-js:latest

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - upload-to-ghcr
    steps:
      - name: Hook to server
        run: curl https://${{ secrets.DEPLOY_URL }}/muz-js-bot